version: "3"

services: 
      db:
        image: postgres
        container_name: db
        ports: 
          - 5432:5432

      api:
        image: biojj/schedule-api
        container_name: schedule-api
        ports:
          - 8080:8080
        environment:
          - SPRING_PROFILES_ACTIVE=prod

      web:
        image: biojj/schedule-web
        container_name: schedule-web
        ports: 
          - 80:80
        depends_on:
          - db
          - api
            
networks: 
    default:
      driver: bridge