version: "3.5"

services: 
      db:
        image: postgres
        container_name: db
        ports: 
          - 5432:5432
        environment:
          - "POSTGRES_USER=postgres"
          - "POSTGRES_PASSWORD=postgres"
          - "POSTGRES_DB=scheduledb"
        
      api:
        image: biojj/schedule-api
        container_name: schedule-api
        ports:
          - 8080:8080
        environment:
        - "SPRING_PROFILES_ACTIVE=prod"
        depends_on:
          - "db"

      web:
        image: biojj/schedule-web
        container_name: schedule-web
        ports: 
          - 80:80
        depends_on:
          - "db"
          - "api"
networks: 
    default:
      driver: bridge
